version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/nike-landing-page-react

hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
